#!/usr/bin/env php

<?php

$birthDate = "1986-01-11";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);

echo "$birthDate : $totalDays\n";
